### ISSUE TITLE
No bike photos

### ISSUE THREAD

**Issue by mikeritter** [apisyouwonthate/build-apis-2#1]
You have to have a bitchin' bike photo or nobody will take you seriously ;-).

Seriously, looking forward to this.

**Comment by philsturgeon** [comment]
Bloody good point. How about if I shove this in About the Author? 

![mud person](https://user-images.githubusercontent.com/67381/52918827-b8196c80-32c9-11e9-8390-556c9525185f.jpeg)

**Comment by mikeritter** [comment]
That's more like it!
